apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  host: {{.Values.db.host | b64enc}}
  port: {{.Values.db.port | b64enc}}
  user: {{.Values.db.user | b64enc}}
  password: {{.Values.db.password | b64enc}}
  database: {{.Values.db.database | b64enc}}
