apiVersion: v1
kind: Service
metadata:
  name: fastapi-app
spec:
  type: ClusterIP # Changed from LoadBalancer to ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: fastapi-app
